services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: bi_rag_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
      - ./data/qdrant_snapshots:/qdrant/snapshots
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - rag_network

  app:
    build: .
    container_name: bi_rag_app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - rag_network
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0

networks:
  rag_network:
    driver: bridge

volumes:
  qdrant_storage:
  qdrant_snapshots: